# General  
train_2d: False
no_eval: False
finetune: False
partial_train: null
model_saved_name: null

# Traning 
epochs: 120
checkpoint_frequency: 60
batch_size: 4
dropout: 0.0
learning_rate: 0.0002 #org 0.0002
weight_decay: 0.01
lr_decay: 0.99 # org 0.99
tasks: ["binocular_left"]
train_mix: False # check this for binocular with monocular
test_task: binocular_left
mo_bi_ratio: 1
mix_contrast_learning: False

# Model
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True
backbone: Unified_Binocular
use_decoder: False
decoder_dim_feat: 128
encoder_left_right_fuse: False
multi_task_head: False # check this for decoder usage
shared_interpreter: True # note the tasks

# Data
data_root: "../dataset/binocular_data/sports/binocular_f243s81"
subset_list: [binocular_align_all] # binocular_align_all_3.7_fix for python 3.7
dt_file: "binocular_data/sports/coco_17_binocular_align_all.pkl"

data_root_h36m: "/mnt/weijiangning-pose-estimation-data/human3.6m"
#data_root_h36m: "../dataset/human3.6m"
subset_list_h36m: [H36M-SH_quarter]
dt_file_h36m: "h36m_sh_conf_cam_source_final.pkl"

clip_len: 243
data_stride: 81
rootrel: True
sample_stride: 1
num_joints: 17
no_conf: False
gt_2d: False

# Loss
lambda_3d_velocity: 20.0
lambda_scale: 0.5
lambda_lv: 0.0
lambda_lg: 0.0
lambda_a: 0.0
lambda_av: 0.0
lambda_r2l: 0.1
lambda_l2r: 0.1
lambda_s2s: 0.1
lambda_contrast: 0.01

# Augmentation
synthetic: False
flip: True
mask_ratio: 0.
mask_T_ratio: 0.
noise: False

# Training
device_ids: [0,1]
#device_ids: [2,3,4,5]